using System;
using System.Collections.Generic;
using System.Text;

namespace ShimizuToolkit.HotkeyWinUI
{
    public enum VirtualKey : uint
    {
        VK_LBUTTON = 0x01, // Left mouse button
        VK_RBUTTON = 0x02, // Right mouse button
        VK_CANCEL = 0x03,
        VK_MBUTTON = 0x04, // Middle mouse button
        VK_XBUTTON1 = 0x05, // X1 mouse button
        VK_XBUTTON2 = 0x06, // X2 mouse button
        VK_BACK = 0x08, // Backspace
        VK_TAB = 0x09,
        VK_CLEAR = 0x0C,
        VK_RETURN = 0x0D,
        VK_SHIFT = 0x10,
        VK_CONTROL = 0x11,
        VK_MENU = 0x12, // Alt
        VK_PAUSE = 0x13,
        VK_CAPITAL = 0x14, // Caps lock
#pragma warning disable CA1069
        VK_KANA = 0x15, // Japan kana
        VK_HANGUL = 0x15, // Korea hangul
#pragma warning restore CA1069
        VK_IME_ON = 0x16,
        VK_JUNJA = 0x17, // IME junja
        VK_FINAL = 0x18, // IME final
#pragma warning disable CA1069
        VK_HANJA = 0x19, // IME hanja
        VK_KANJI = 0x19, // IME kanji
#pragma warning restore CA1069
        VK_IME_OFF = 0x1A, // IME off
        VK_ESCAPE = 0x1B,
        VK_CONVERT = 0x1C, // IME convert
        VK_NONCONVERT = 0x1D, // IME nonconvert
        VK_ACCEPT = 0x1E, // IME accept
        VK_MODECHANGE = 0x1F, // IME mode change request
        VK_SPACE = 0x20,
        VK_PRIOR = 0x21, // Page up
        VK_NEXT = 0x22, // Page down
        VK_END = 0x23,
        VK_HOME = 0x24,
        VK_LEFT = 0x25,
        VK_UP = 0x26,
        VK_RIGHT = 0x27,
        VK_DOWN = 0x28,
        VK_SELECT = 0x29,
        VK_PRINT = 0x2A,
        VK_EXECUTE = 0x2B,
        VK_SNAPSHOT = 0x2C, // Print screen
        VK_INSERT = 0x2D,
        VK_DELETE = 0x2E,
        VK_HELP = 0x2F,
        VK_0 = 0x30,
        VK_1 = 0x31,
        VK_2 = 0x32,
        VK_3 = 0x33,
        VK_4 = 0x34,
        VK_5 = 0x35,
        VK_6 = 0x36,
        VK_7 = 0x37,
        VK_8 = 0x38,
        VK_9 = 0x39,
        VK_A = 0x41,
        VK_B = 0x42,
        VK_C = 0x43,
        VK_D = 0x44,
        VK_E = 0x45,
        VK_F = 0x46,
        VK_G = 0x47,
        VK_H = 0x48,
        VK_I = 0x49,
        VK_J = 0x4A,
        VK_K = 0x4B,
        VK_L = 0x4C,
        VK_M = 0x4D,
        VK_N = 0x4E,
        VK_O = 0x4F,
        VK_P = 0x50,
        VK_Q = 0x51,
        VK_R = 0x52,
        VK_S = 0x53,
        VK_T = 0x54,
        VK_U = 0x55,
        VK_V = 0x56,
        VK_W = 0x57,
        VK_X = 0x58,
        VK_Y = 0x59,
        VK_Z = 0x5A,
        VK_LWIN = 0x5B, // Left Windows key
        VK_RWIN = 0x5C, // Right Windows key
        VK_APPS = 0x5D, // Applications key
        VK_SLEEP = 0x5F, // Sleep key
        VK_NUMPAD0 = 0x60,
        VK_NUMPAD1 = 0x61,
        VK_NUMPAD2 = 0x62,
        VK_NUMPAD3 = 0x63,
        VK_NUMPAD4 = 0x64,
        VK_NUMPAD5 = 0x65,
        VK_NUMPAD6 = 0x66,
        VK_NUMPAD7 = 0x67,
        VK_NUMPAD8 = 0x68,
        VK_NUMPAD9 = 0x69,
        VK_MULTIPLY = 0x6A, // *
        VK_ADD = 0x6B, // +
        VK_SEPARATOR = 0x6C, // _
        VK_SUBTRACT = 0x6D, // -
        VK_DECIMAL = 0x6E, // Decimal key
        VK_DIVIDE = 0x6F, // /
        VK_F1 = 0x70,
        VK_F2 = 0x71,
        VK_F3 = 0x72,
        VK_F4 = 0x73,
        VK_F5 = 0x74,
        VK_F6 = 0x75,
        VK_F7 = 0x76,
        VK_F8 = 0x77,
        VK_F9 = 0x78,
        VK_F10 = 0x79,
        VK_F11 = 0x7A,
        VK_F12 = 0x7B,
        VK_F13 = 0x7C,
        VK_F14 = 0x7D,
        VK_F15 = 0x7E,
        VK_F16 = 0x7F,
        VK_F17 = 0x80,
        VK_F18 = 0x81,
        VK_F19 = 0x82,
        VK_F20 = 0x83,
        VK_F21 = 0x84,
        VK_F22 = 0x85,
        VK_F23 = 0x86,
        VK_F24 = 0x87,
        VK_NUMLOCK = 0x90, // Num lock
        VK_SCROLL = 0x91, // Scroll lock
        VK_LSHIFT = 0xA0, // Left shift
        VK_RSHIFT = 0xA1, // Right shift
        VK_LCONTROL = 0xA2, // Left control
        VK_RCONTROL = 0xA3, // Right control
        VK_LMENU = 0xA4, // Left menu (Alt)
        VK_RMENU = 0xA5, // Right menu (Alt)
        VK_BROWSER_BACK = 0xA6, // Browser back
        VK_BROWSER_FORWARD = 0xA7, // Browser forward
        VK_BROWSER_REFRESH = 0xA8, // Browser refresh
        VK_BROWSER_STOP = 0xA9, // Browser stop
        VK_BROWSER_SEARCH = 0xAA, // Browser search
        VK_BROWSER_FAVORITES = 0xAB, // Browser favorites
        VK_BROWSER_HOME = 0xAC, // Browser home
        VK_VOLUME_MUTE = 0xAD,
        VK_VOLUME_DOWN = 0xAE,
        VK_VOLUME_UP = 0xAF,
        VK_MEDIA_NEXT_TRACK = 0xB0, // Next track
        VK_MEDIA_PREV_TRACK = 0xB1, // Previous track
        VK_MEDIA_STOP = 0xB2, // Stop media
        VK_MEDIA_PLAY_PAUSE = 0xB3, // Play/pause media
        VK_LAUNCH_MAIL = 0xB4, // Launch mail
        VK_LAUNCH_MEDIA_SELECT = 0xB5, // Launch media select
        VK_LAUNCH_APP1 = 0xB6, // Launch application 1
        VK_LAUNCH_APP2 = 0xB7, // Launch application 2
        VK_OEM_1 = 0xBA, // ; : (Colon key, for US ANSI keyboards)
        VK_OEM_PLUS = 0xBB, // + = (Plus key)
        VK_OEM_COMMA = 0xBC,// , < (Comma key)
        VK_OEM_MINUS = 0xBD, // - _ (Minus key)
        VK_OEM_PERIOD = 0xBE, // . > (Period key)
        VK_OEM_2 = 0xBF, // / ? (Slash key, for US ANSI keyboards)
        VK_OEM_3 = 0xC0, // ` ~ (Grave key, for US ANSI keyboards)
        VK_GAMEPAD_A = 0xC3, // Gamepad A
        VK_GAMEPAD_B = 0xC4, // Gamepad B
        VK_GAMEPAD_X = 0xC5, // Gamepad X
        VK_GAMEPAD_Y = 0xC6, // Gamepad Y
        VK_GAMEPAD_RIGHT_SHOULDER = 0xC7, // Gamepad right shoulder
        VK_GAMEPAD_LEFT_SHOULDER = 0xC8, // Gamepad left shoulder
        VK_GAMEPAD_LEFT_TRIGGER = 0xC9, // Gamepad left trigger
        VK_GAMEPAD_RIGHT_TRIGGER = 0xCA, // Gamepad right trigger
        VK_GAMEPAD_DPAD_UP = 0xCB, // Gamepad D-pad up
        VK_GAMEPAD_DPAD_DOWN = 0xCC, // Gamepad D-pad down
        VK_GAMEPAD_DPAD_LEFT = 0xCD, // Gamepad D-pad left
        VK_GAMEPAD_DPAD_RIGHT = 0xCE, // Gamepad D-pad right
        VK_GAMEPAD_MENU = 0xCF, // Gamepad menu
        VK_GAMEPAD_VIEW = 0xD0, // Gamepad view
        VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON = 0xD1, // Gamepad left thumbstick button
        VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = 0xD2, // Gamepad right thumbstick button
        VK_GAMEPAD_LEFT_THUMBSTICK_UP = 0xD3, // Gamepad left thumbstick up
        VK_GAMEPAD_LEFT_THUMBSTICK_DOWN = 0xD4, // Gamepad left thumbstick down
        VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT = 0xD5, // Gamepad left thumbstick right
        VK_GAMEPAD_LEFT_THUMBSTICK_LEFT = 0xD6, // Gamepad left thumbstick left
        VK_GAMEPAD_RIGHT_THUMBSTICK_UP = 0xD7, // Gamepad right thumbstick up
        VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN = 0xD8, // Gamepad right thumbstick down
        VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = 0xD9, // Gamepad right thumbstick right
        VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT = 0xDA, // Gamepad right thumbstick left
        VK_OEM_4 = 0xDB, // [ { (Left bracket key, for US ANSI keyboards)
        VK_OEM_5 = 0xDC, // \ | (Backslash key, for US ANSI keyboards)
        VK_OEM_6 = 0xDD, // ] } (Right bracket key, for US ANSI keyboards)
        VK_OEM_7 = 0xDE, // ' " (Apostrophe key, for US ANSI keyboards)
        VK_OEM_8 = 0xDF, // OEM specific, Right ctrl For Canada CSA Keyboard
        VK_OEM_0xE1 = 0xE1, // OEM specific
        VK_OEM_102 = 0xE2, // \ | (OEM 102 key, for UK/EURO keyboards)
        VK_OEM_0xE3 = 0xE3, // OEM specific
        VK_OEM_0xE4 = 0xE4, // OEM specific
        VK_PROCESSKEY = 0xE5, // IME process key
        VK_OEM_0xE6 = 0xE6, // OEM specific
        VK_PACKET = 0xE7, // Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods.
        VK_OEM_0xE9 = 0xE9, // OEM specific
        VK_OEM_0xEA = 0xEA, // OEM specific
        VK_OEM_0xEB = 0xEB, // OEM specific
        VK_OEM_0xEC = 0xEC, // OEM specific
        VK_OEM_0xED = 0xED, // OEM specific
        VK_OEM_0xEF = 0xEF, // OEM specific
        VK_OEM_0xF0 = 0xF0, // OEM specific
        VK_OEM_0xF1 = 0xF1, // OEM specific
        VK_OEM_0xF2 = 0xF2, // OEM specific
        VK_OEM_0xF3 = 0xF3, // OEM specific
        VK_OEM_0xF4 = 0xF4, // OEM specific
        VK_OEM_0xF5 = 0xF5, // OEM specific
        VK_ATTN = 0xF6, // Attn key
        VK_CRSEL = 0xF7, // CrSel key
        VK_EXSEL = 0xF8, // ExSel key
        VK_EREOF = 0xF9, // Erase EOF key
        VK_PLAY = 0xFA, // Play key
        VK_ZOOM = 0xFB, // Zoom key
        VK_NONAME = 0xFC, // Reserved
        VK_PA1 = 0xFD, // PA1 key
        VK_OEM_CLEAR = 0xFE, // Clear key
    }
}
